local STRINGS = GLOBAL.STRINGS
--local wilson_ds  = STRINGS.CHARACTERS.GENERIC.DESCRIBE
--local wurt_ds    = STRINGS.CHARACTERS.WURT.DESCRIBE
STRINGS.UI.CRAFTING_FILTERS.CPITEMS="压缩物品"--制作栏的名字，鼠标放上去会显示

-- 压缩采下的草
STRINGS.RECIPE_DESC.CP_CUTGRASS = "哦，这是压缩的采下的草" -- 物体的制作栏描述
STRINGS.NAMES.CP_CUTGRASS = "压缩采下的草" --物品名称

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_CUTGRASS = "割下来的草，一种压缩工艺，可用于制作和合成其他耐久更高的东西。" 
STRINGS.CHARACTERS.WALTER.DESCRIBE.CP_CUTGRASS  = "如果削薄一点就可以用它来吹口哨！"
STRINGS.CHARACTERS.WURT.DESCRIBE.CP_CUTGRASS	= "它是我的重剑了。" -- its my epee now







-- 压缩树枝
STRINGS.RECIPE_DESC.CP_TWIGS = "哦，这是压缩的树枝" -- 物体的制作栏描述
STRINGS.NAMES.CP_TWIGS = "压缩树枝" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_TWIGS = "一篮小树枝。"
STRINGS.CHARACTERS.WURT.DESCRIBE.CP_TWIGS = "一篮木棍，浮浪噗。"


-- 压缩火炬
STRINGS.RECIPE_DESC.CP_TORCH = "可携带的压缩光源" -- 物体的制作栏描述
STRINGS.NAMES.CP_TORCH = "压缩火矩" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_TORCH = "压缩式驱赶黑暗的东西。"
--STRINGS.CHARACTERS.WURT.DESCRIBE.CP_TORCH = " "

-- 压缩打火机
STRINGS.RECIPE_DESC.CP_LIGHTER = "足够强大的火焰能够在暴风雨中存活。" -- 物体的制作栏描述
STRINGS.NAMES.CP_LIGHTER = "压缩薇洛的打火机" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_LIGHTER = "她的幸运打火机，强化版本。"
--STRINGS.CHARACTERS.WURT.DESCRIBE.CP_LIGHTER = " "

-- 压缩伯尼
STRINGS.RECIPE_DESC.CP_BERNIE_INACTIVE = "这个疯狂的世界总有你熟悉的压缩人。" -- 物体的制作栏描述
STRINGS.NAMES.CP_BERNIE_INACTIVE = "压缩伯尼" --物品名称
STRINGS.NAMES.CP_BERNIE_ACTIVE = "压缩伯尼" --物品名称
STRINGS.NAMES.CP_BERNIE_BIG = "压缩伯尼！" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_BERNIE_ACTIVE = "哇！你的压缩小熊被幽灵缠身了？受了诅咒吗？"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_BERNIE_INACTIVE = "压缩的它全烧焦了。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_BERNIE_BIG = "千万不要惹薇洛，我是认真的。"
--STRINGS.CHARACTERS.WURT.DESCRIBE.CP_BERNIE_ACTIVE = " "






-- 压缩木头
STRINGS.RECIPE_DESC.CP_LOG = "哦，这是压缩的木头" -- 物体的制作栏描述
STRINGS.NAMES.CP_LOG = "压缩木头" --物品名称
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_LOG.BURNING = "好烫的木头堆！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_LOG = "又大又重的木头堆。"

-- 压缩木板
STRINGS.RECIPE_DESC.CP_BOARDS = "更平直更粗壮的木头。" -- 物体的制作栏描述
STRINGS.NAMES.CP_BOARDS = "压缩木板" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_BOARDS = "压缩木板。"


-- 压缩燧石
STRINGS.RECIPE_DESC.CP_FLINT = "哦，这是压缩的燧石" -- 物体的制作栏描述
STRINGS.NAMES.CP_FLINT = "压缩燧石" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_FLINT = "密度高的非常尖的石头。"
--STRINGS.CHARACTERS.WURT.DESCRIBE.CP_FLINT = "一篮木棍，浮浪噗。"

-- 玻璃转弹珠
STRINGS.RECIPE_DESC.TRINKET_1 = "这玩意儿……好使吗？" -- 物体的制作栏描述
STRINGS.NAMES.TRANSMUTE_TRINKET_1 = "熔化的弹珠" --浴火勋章手搓
STRINGS.NAMES.CP_TRANSMUTE_TRINKET_1 = "熔化的弹珠" --威屌手搓
STRINGS.NAMES.CP_WALTER_TRANSMUTE_TRINKET_1 = "熔化的弹珠" --沃尔特手搓

-- 压缩警告表
STRINGS.RECIPE_DESC.CP_POCKETWATCH_WEAPON = "哦，这是压缩的警钟" -- 物体的制作栏描述
STRINGS.NAMES.CP_POCKETWATCH_WEAPON = "压缩警钟" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_POCKETWATCH_WEAPON = "坏事发生只是时间问题，我想说这要加速了。"

-- 压缩弹弓
STRINGS.RECIPE_DESC.CP_SLINGSHOT = "哦，这是压缩的可靠的弹弓" -- 物体的制作栏描述
STRINGS.NAMES.CP_SLINGSHOT = "压缩可靠的弹弓" --物品名称
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOT = "玻璃宇宙的梦魇。"
-- 压缩弹药
STRINGS.NAMES.CP_SLINGSHOTAMMO_FREEZE = "压缩冰冻弹药"
STRINGS.RECIPE_DESC.CP_SLINGSHOTAMMO_FREEZE = "把敌人冰冻在原地，我是说真的！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOTAMMO_FREEZE = "即将打出的压缩弹药。"

STRINGS.NAMES.CP_SLINGSHOTAMMO_ROCK = "压缩鹅卵石"
STRINGS.RECIPE_DESC.CP_SLINGSHOTAMMO_ROCK = "简单，低效。对比来说。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOTAMMO_ROCK = "即将打出的压缩弹药。"

STRINGS.NAMES.CP_SLINGSHOTAMMO_GOLD = "压缩黄金弹药"
STRINGS.RECIPE_DESC.CP_SLINGSHOTAMMO_GOLD = "高级的压缩，成倍的有效。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOTAMMO_GOLD = "即将打出的压缩弹药。"

STRINGS.NAMES.CP_SLINGSHOTAMMO_MARBLE = "压缩大理石弹"
STRINGS.RECIPE_DESC.CP_SLINGSHOTAMMO_MARBLE = "压缩很珍贵，千万别弄丢！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOTAMMO_MARBLE = "即将打出的压缩弹药。"

STRINGS.NAMES.CP_SLINGSHOTAMMO_POOP = "压缩便便弹"
STRINGS.RECIPE_DESC.CP_SLINGSHOTAMMO_POOP = "成倍的恶心，能使头目分心。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOTAMMO_POOP = "压缩粪便弹道。"

STRINGS.NAMES.CP_SLINGSHOTAMMO_SLOW = "压缩减速弹药"
STRINGS.RECIPE_DESC.CP_SLINGSHOTAMMO_SLOW = "物理学不存在了？"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOTAMMO_SLOW = "即将打出的压缩弹药。"

STRINGS.NAMES.CP_SLINGSHOTAMMO_THULECITE = "压缩诅咒弹药"
STRINGS.RECIPE_DESC.CP_SLINGSHOTAMMO_THULECITE = "会出什么问题？我不好说。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_SLINGSHOTAMMO_THULECITE = "即将打出的压缩弹药。"

STRINGS.NAMES.CP_TRINKET_1 = "压缩融化的弹珠"
STRINGS.RECIPE_DESC.CP_TRINKET_1 = "我想这应该是最适合弹弓的！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_TRINKET_1 = "融化了。或许薇洛和他们相处愉快？"
-- END


--压缩拳击袋
--[[
STRINGS.NAMES.CP_PUNCHINGBAG = "压缩拳击袋"
STRINGS.RECIPE_DESC.CP_PUNCHINGBAG = "测试武器的超模程度。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CP_PUNCHINGBAG = "它配备了一个精心校准的“哎哟”仪表，支持六位数显示。"
]]


